server:
  port: 8080
--- # 数据源配置
spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hotel
      username: root
      password: root

captcha:
  # 验证码类型 math 数组计算 char 字符验证
  type: MATH
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: line
  # 数字验证码位数
  numberLength: 1
  # 字符验证码长度
  charLength: 4

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring:
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码(如没有密码请注释掉)
#    password:
    # 连接超时时间
    timeout: 100s
    # 是否开启ssl
    ssl: false